# Generated by Django 3.1.7 on 2021-03-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datarepo', '0003_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
